version: "3.7"

networks:
    tabiat-network:
        driver: bridge

services:
    app:
        build:
            # args:
            #     user: root
            #     uid: 0
            context: ./
            dockerfile: Dockerfile
        image: laravel8-php-fpm-80
        container_name: tabiat-app
        restart: unless-stopped
        working_dir: /var/www/html/tabiat
        volumes:
            - ./:/var/www/html/tabiat
        networks:
            - tabiat-network

    db:        
        image: mysql:5.7
        container_name: tabiat-mysql
        restart: unless-stopped
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            # - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - tabiat-datavolume:/var/lib/mysql
        networks:
            - tabiat-network

    nginx:
        image: nginx:alpine
        container_name: tabiat-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html/tabiat
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - tabiat-network

volumes:
    tabiat-datavolume:
